"""db.py — practice_sessions persistence in Neon Postgres. Plain psycopg,
no ORM. user_id is the neon_auth.user UUID (see pipeline/auth.py)."""
import json
import os

import psycopg
from psycopg.rows import dict_row

_SCHEMA = """
CREATE TABLE IF NOT EXISTS practice_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    transcript TEXT NOT NULL,
    duration_sec NUMERIC,
    recording_key TEXT,
    linguistics JSONB NOT NULL,
    pauses JSONB NOT NULL,
    prosody JSONB NOT NULL,
    findings JSONB NOT NULL,
    delivery_score JSONB NOT NULL,
    answer_grading JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_practice_sessions_user_created
    ON practice_sessions (user_id, created_at DESC);
"""


def run_migrations():
    """Idempotent; safe to call on every startup. Uses the direct
    (unpooled) connection — DDL over PgBouncer's transaction pooling is
    unreliable."""
    url = os.environ["DATABASE_URL_UNPOOLED"]
    with psycopg.connect(url, autocommit=True) as conn:
        conn.execute(_SCHEMA)


def _pooled():
    return psycopg.connect(os.environ["DATABASE_URL"], row_factory=dict_row)


def insert_session(session_id: str, user_id: str, question: str, transcript: str,
                    duration_sec: float, recording_key: str | None, linguistics: dict,
                    pauses: dict, prosody: dict, findings: list, delivery_score: dict,
                    answer_grading: dict | None) -> None:
    """session_id is generated by the caller (not the DB default) so the
    recording's bucket key can be built before the row is inserted."""
    with _pooled() as conn:
        conn.execute(
            """
            INSERT INTO practice_sessions
                (id, user_id, question, transcript, duration_sec, recording_key,
                 linguistics, pauses, prosody, findings, delivery_score, answer_grading)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (session_id, user_id, question, transcript, duration_sec, recording_key,
             json.dumps(linguistics), json.dumps(pauses), json.dumps(prosody),
             json.dumps(findings), json.dumps(delivery_score),
             json.dumps(answer_grading) if answer_grading is not None else None),
        )
        conn.commit()


def list_sessions(user_id: str) -> list[dict]:
    with _pooled() as conn:
        rows = conn.execute(
            """
            SELECT id, question, created_at, duration_sec,
                   delivery_score->'score' AS delivery_score,
                   answer_grading->'correctness_score' AS correctness_score
            FROM practice_sessions
            WHERE user_id = %s
            ORDER BY created_at DESC
            """,
            (user_id,),
        ).fetchall()
        return [
            {
                "id": str(r["id"]),
                "question": r["question"],
                "created_at": r["created_at"].isoformat(),
                "duration_sec": float(r["duration_sec"]) if r["duration_sec"] is not None else None,
                "delivery_score": r["delivery_score"],
                "correctness_score": r["correctness_score"],
            }
            for r in rows
        ]


def get_session(session_id: str, user_id: str) -> dict | None:
    with _pooled() as conn:
        row = conn.execute(
            "SELECT * FROM practice_sessions WHERE id = %s AND user_id = %s",
            (session_id, user_id),
        ).fetchone()
        if not row:
            return None
        return {
            "id": str(row["id"]),
            "question": row["question"],
            "transcript": row["transcript"],
            "duration_sec": float(row["duration_sec"]) if row["duration_sec"] is not None else None,
            "recording_key": row["recording_key"],
            "linguistics": row["linguistics"],
            "pauses": row["pauses"],
            "prosody": row["prosody"],
            "findings": row["findings"],
            "delivery_score": row["delivery_score"],
            "answer_grading": row["answer_grading"],
            "created_at": row["created_at"].isoformat(),
        }
